// Package harness is the registry of third-party agent harnesses (Claude Code,
// Cursor, Codex and the rest) that a library scan searches: where each one
// keeps its commands, skills, prompts, agents and instruction documents, for
// the user and for a project, and which agentimport format reads them.
//
// The data is harnesses.json, generated by tools/gen-harnesses from the cli
// repository's harness lists and extended by hand for the directories those
// lists do not hold. Every directory is relative to the user's home (User) or
// to a repository root (Project); nothing here is an absolute path.
package harness

import (
	"os"
	"path/filepath"
	"strings"
)

// Kinds a harness can hold as files. Belai's own settings kinds (process,
// budget, rewrite, provider, repo, crew) are not in other harnesses.
const (
	Command  = "command"
	Skill    = "skill"
	Prompt   = "prompt"
	Agent    = "agent"
	Document = "document"
	// Hook is a harness's lifecycle hooks: a hooks block in a settings file, a
	// hooks file, or a directory of hook scripts.
	Hook = "hook"
)

// Shapes of the files in a directory.
const (
	// MDFile: one <name>.md per item, directly in the directory.
	MDFile = "md-file"
	// SkillDir: one <name>/SKILL.md per item.
	SkillDir = "skill-dir"
	// DocFile: the directory holds fixed file names (AGENTS.md, CLAUDE.md).
	DocFile = "doc-file"
	// JSONKey: the user and project entries are JSON files (not directories),
	// and the item is the value of the KindDirs.Key key inside each one, such as
	// the `hooks` key of Claude Code's settings.json. Nothing else in the file is
	// read.
	JSONKey = "json-key"
	// JSONFile: the user and project entries are JSON files that are the item
	// themselves, one item per file (Codex's hooks.json).
	JSONFile = "json-file"
	// Unsupported: the harness stores this kind in a format Belai does not read
	// (for example TOML). It is reported, never read.
	Unsupported = "unsupported"
)

// KindDirs is where one harness keeps one kind.
type KindDirs struct {
	// User are home-relative directories, "~/" prefix included.
	User []string `json:"user,omitempty"`
	// Project are repository-relative directories, no leading slash.
	Project []string `json:"project,omitempty"`
	// Shape is one of the shape constants.
	Shape string `json:"shape"`
	// Files names the fixed files of a DocFile shape.
	Files []string `json:"files,omitempty"`
	// Key names the key a JSONKey shape reads from each file ("hooks").
	Key string `json:"key,omitempty"`
}

// Harness is one agent harness.
type Harness struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Detect are home-relative paths whose presence means it is installed.
	Detect []string `json:"detect"`
	// Format is the agentimport format that reads this harness's files.
	Format string `json:"format"`
	// Aliases are other ids the cli sources use for this harness (for example
	// openai-codex for codex). ByID resolves them.
	Aliases []string `json:"aliases,omitempty"`
	// Dirs is keyed by kind (Command, Skill, Prompt, Agent, Document, Hook).
	Dirs map[string]KindDirs `json:"dirs"`
}

// All returns every known harness in a stable order.
func All() []Harness { return registry() }

// ByID finds one harness.
func ByID(id string) (Harness, bool) {
	for _, h := range registry() {
		if h.ID == id {
			return h, true
		}
		for _, a := range h.Aliases {
			if a == id {
				return h, true
			}
		}
	}
	return Harness{}, false
}

// Installed reports whether any of the harness's detect paths exists under home.
func (h Harness) Installed(home string) bool {
	for _, d := range h.Detect {
		if _, err := os.Stat(Expand(home, d)); err == nil {
			return true
		}
	}
	return false
}

// Expand resolves a "~/"-prefixed path against home.
func Expand(home, p string) string {
	if p == "~" {
		return home
	}
	if strings.HasPrefix(p, "~/") {
		return filepath.Join(home, p[2:])
	}
	return p
}
